- name: Generate cinder.conf
  template:
    src: cinder.conf.j2
    dest: /tmp/cinder.conf

- name: Read cinder.conf into memory
  slurp:
    src: "/tmp/cinder.conf"
  register: "cinder_conf"

# Upload and create pod specific configmap
- name: Upload config files
  template:
    src: "{{item}}"
    dest: /tmp/{{item}}
    backup: yes
    mode: 0644
  with_items:
    - cinder-wsgi.conf

- name: Read cinder-wsgi into memory
  slurp:
    src: "/tmp/cinder-wsgi.conf"
  register: "cinder_wsgi_conf"

- name: Create cinder-api configmaps
  ignore_errors: yes
  k8s_v1_config_map:
    name: cinder-api
    namespace: "{{ namespace }}"
    state: present
    debug: yes
    labels:
      service: cinder
    data:
      config.json: |
        {
            "command": "httpd -DFOREGROUND",
            "config_files": [
                {
                    "source": "/var/lib/kolla/config_files/cinder.conf",
                    "dest": "/etc/cinder/cinder.conf",
                    "owner": "cinder",
                    "perm": "0600"
                },
                {
                    "source": "/var/lib/kolla/config_files/cinder-wsgi.conf",
                    "dest": "/etc/httpd/conf.d/cinder-wsgi.conf",
                    "owner": "cinder",
                    "perm": "0600"
                }
            ],
            "permissions": [
                {
                    "path": "/var/lib/cinder",
                    "owner": "cinder:cinder",
                    "recurse": true
                },
                {
                    "path": "/var/log/kolla/cinder",
                    "owner": "cinder:cinder",
                    "recurse": true
                }
            ]
        }

      cinder.conf: |
        {{cinder_conf['content'] | b64decode}}

      cinder-wsgi.conf: |
        {{cinder_wsgi_conf['content'] | b64decode}}


- name: Create cinder-scheduler configmaps
  ignore_errors: yes
  k8s_v1_config_map:
    name: cinder-scheduler
    namespace: "{{ namespace }}"
    state: present
    debug: yes
    labels:
      service: cinder-scheduler
    data:
      config.json: |
        {
            "command": "cinder-scheduler --config-file /var/lib/kolla/config_files/cinder.conf",
            "config_files": [
                {
                    "source": "/var/lib/kolla/config_files/cinder.conf",
                    "dest": "/etc/cinder/cinder.conf",
                    "owner": "cinder",
                    "perm": "0600"
                }
            ],
            "permissions": [
                {
                    "path": "/var/lib/cinder",
                    "owner": "cinder:cinder",
                    "recurse": true
                },
                {
                    "path": "/var/log/kolla/cinder",
                    "owner": "cinder:cinder",
                    "recurse": true
                }
            ]
        }

      cinder.conf: |
        {{cinder_conf['content'] | b64decode}}

