---
- include: hiera.yml
- include: enabled_backends.yml

- name: Generate config files
  config_template:
    src: cinder.conf.j2
    dest: /tmp/cinder.conf
    config_type: ini

- name: Read configs into memory
  slurp:
    src: "/tmp/cinder.conf"
  register: "cinder_conf"

- include: config_maps.yml
- include: init-jobs.yml
- include: cinder-api.yml
- include: cinder-scheduler.yml
- include: cinder-volume.yml

